### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by msmichellegar** [FounderLondon/website#2]
Wireframes for reference.

![founder wireframe 1](https://cloud.githubusercontent.com/assets/10683087/9357130/1b7d5f08-467d-11e5-8d6d-67b8c77b6fd6.png)

**Comment by SimonLab** [comment]
wireframes from Founder
![wireframe1](https://cloud.githubusercontent.com/assets/6057298/9413509/1c792b5e-482a-11e5-84ad-36fa8c6984ab.jpg)
![wireframe2](https://cloud.githubusercontent.com/assets/6057298/9413511/1c7f3a80-482a-11e5-8326-150f7976667c.jpg)
![wireframe3](https://cloud.githubusercontent.com/assets/6057298/9413510/1c7bf91a-482a-11e5-8215-61c3691f75a5.jpg)

**Comment by SimonLab** [comment]
![founder-wireframe-2](https://cloud.githubusercontent.com/assets/6057298/9900670/3d162fee-5c5a-11e5-8d30-a75adf4bebb9.png)

![founder-wireframe-1](https://cloud.githubusercontent.com/assets/6057298/9900680/4aaf95d2-5c5a-11e5-8ace-f594436d50ca.png)

**Comment by msmichellegar** [comment]
:+1:
